### ISSUE TITLE
Traceback occurs when using -T with float

### ISSUE THREAD

**Issue by jftuga** [jftuga/tcpscan#1]
```

$ tcpscan.py -T 0.5 192.168.1.1
Traceback (most recent call last):
  File "/Users/john/bin/tcpscan.py", line 568, in <module>
    main()
  File "/Users/john/bin/tcpscan.py", line 423, in main
    max_workers = int(args.threads)
ValueError: invalid literal for int() with base 10: '0.5'

```

**Comment by jftuga** [comment]
This is fixed in v1.34
